from typing import Dict, Any, List, Optional
from backend.database.repositories.campaign_repository import CampaignRepository
from backend.graph.workflow import run_campaign_studio_workflow, run_campaign_execution_workflow

class CampaignService:
    @staticmethod
    def list_campaigns() -> List[Dict[str, Any]]:
        return CampaignRepository.list_all()

    @staticmethod
    def create_campaign(
        name: str,
        description: Optional[str],
        type_str: str,
        segment_id: Optional[str],
        content_template: str
    ) -> Dict[str, Any]:
        return CampaignRepository.create(name, description, type_str, segment_id, content_template)

    @staticmethod
    def trigger_campaign(campaign_id: str, background_tasks) -> Dict[str, str]:
        campaign = CampaignRepository.get_by_id(campaign_id)
        if not campaign:
            raise ValueError("Campaign not found")
        if campaign["status"] == "active":
            raise ValueError("Campaign is already running or active.")
            
        background_tasks.add_task(run_campaign_execution_workflow, campaign_id)
        return {"message": "Campaign queued for dispatch", "status": "queued"}

    @staticmethod
    def approve_studio_campaign(
        marketing_goal: str,
        segment_name: str,
        segment_rules: List[Dict[str, Any]],
        channel: str,
        content_template: str,
        description: Optional[str]
    ) -> Dict[str, Any]:
        # 1. Create segment
        seg_description = f"Segment automatically generated by Campaign Studio for goal: '{marketing_goal}'"
        seg_id = CampaignRepository.create_segment(segment_name, seg_description, segment_rules)
        
        # 2. Create campaign
        camp_name = f"Studio - {segment_name}"
        camp_description = description or f"AI Campaign drafted for goal: '{marketing_goal}'"
        return CampaignRepository.create(camp_name, camp_description, channel, seg_id, content_template)

    @staticmethod
    def run_planning_workflow(marketing_goal: str) -> Dict[str, Any]:
        return run_campaign_studio_workflow(marketing_goal)
